### ISSUE TITLE
Buffer Underflow when Reading Character File

### ISSUE THREAD

**Issue by strawstack** [Kakoen/valheim-save-tools#25]
When I use the following command to attempt to convert a character file (fch) to JSON, I get a `java.nio.BufferUnderflowException`.

Command: `java -jar valheim-save-tools.jar -v strawstack.fch strawstack.json`

Full Error Message: 

```
INFO Reading from C:\Users\rhsha\Documents\5 valheim backup\10 character\strawstack.fch
WARN Character version 36 encountered, last tested version was 33
WARN Map version 7 encountered, but latest tested map version was 4
WARN Object at 4194505 with size 43444 was not fully read, 43436 bytes remain
WARN At net.kakoen.valheim.save.archive.character.WorldPlayerData.<init>(WorldPlayerData.java:39)
WARN Object at 4 with size 4283427 was not fully read, 45482 bytes remain
WARN At net.kakoen.valheim.save.archive.ValheimCharacter.<init>(ValheimCharacter.java:41)
WARN File not fully read, 68 bytes remain
Exception in thread "main" java.nio.BufferUnderflowException
        at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:294)
        at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:771)
        at net.kakoen.valheim.save.parser.ZPackage.readBytes(ZPackage.java:136)
        at net.kakoen.valheim.save.archive.character.MinimapData.<init>(MinimapData.java:38)
        at net.kakoen.valheim.save.archive.character.WorldPlayerData.lambda$new$0(WorldPlayerData.java:39)
        at net.kakoen.valheim.save.parser.ZPackage.readFixedSizeObject(ZPackage.java:163)
        at net.kakoen.valheim.save.parser.ZPackage.readLengthPrefixedObject(ZPackage.java:187)
        at net.kakoen.valheim.save.archive.character.WorldPlayerData.<init>(WorldPlayerData.java:39)
        at net.kakoen.valheim.save.archive.ValheimCharacter.lambda$new$1(ValheimCharacter.java:58)
        at net.kakoen.valheim.save.parser.ZPackage.readFixedSizeObject(ZPackage.java:163)
        at net.kakoen.valheim.save.parser.ZPackage.readLengthPrefixedObject(ZPackage.java:187)
        at net.kakoen.valheim.save.archive.ValheimCharacter.<init>(ValheimCharacter.java:41)
        at net.kakoen.valheim.cli.SaveToolsCLI.readValheimArchive(SaveToolsCLI.java:123)
        at net.kakoen.valheim.cli.SaveToolsCLI.main(SaveToolsCLI.java:52)
```

I was successfully able to convert a world file to JSON.

**Comment by Kakoen** [comment]
Should be fixed in latest snapshot build, and upcoming verison 1.1.1. If it happens again, please create a new issue with an upload of your character file, so I can look at it in detail.
