### ISSUE TITLE
Valheim-save-tools throws an error with new worlds (probably Hildir's Request patch)

### ISSUE THREAD

**Issue by maleneDev** [Kakoen/valheim-save-tools#86]
**OS: Win 10
Java: 17.0.10
Valheim-Save-Tools: 1.1.1**

I was trying to parse some logs from my .db world but got an error. Warning says that new valheim worlds are not supported.
Last version of _valheim-save-tools_ was published in april 2023, since then only patch was applied to the game - Hildir's Request.
So my guess is Hildir's Request somehow broke parser.
Decided to leave than info here!

```
PS C:\Users\Malene\valheim-save-tools> java -jar valheim-save-tools.jar .\12312331321.db mysave.json
INFO Reading from C:\Users\Malene\valheim-save-tools\.\12312331321.db
WARN WARNING: world version is 33, the maximum tested world version is 29
WARN Object at 44 with size 0 was not fully read, -36527902 bytes remain
WARN At net.kakoen.valheim.save.archive.save.Zdo.<init>(Zdo.java:79)
WARN Fixed size object at 44 was read past expected size 0, 36527902 extra bytes were read
WARN At net.kakoen.valheim.save.archive.save.Zdo.<init>(Zdo.java:79)
WARN File not fully read, 66607123 bytes remain
Exception in thread "main" java.lang.IllegalStateException: Reading string at 36527942 with length 144936998 would exceed the end of the file
        at net.kakoen.valheim.save.parser.ZPackage.readString(ZPackage.java:348)
        at net.kakoen.valheim.save.archive.save.Zdo.readValue(Zdo.java:178)
        at net.kakoen.valheim.save.archive.save.Zdo.lambda$new$0(Zdo.java:155)
        at net.kakoen.valheim.save.parser.ZPackage.readFixedSizeObject(ZPackage.java:166)
        at net.kakoen.valheim.save.parser.ZPackage.readLengthPrefixedObject(ZPackage.java:190)
        at net.kakoen.valheim.save.archive.save.Zdo.<init>(Zdo.java:79)
        at net.kakoen.valheim.save.archive.ValheimSaveArchive.loadZdos(ValheimSaveArchive.java:101)
        at net.kakoen.valheim.save.archive.ValheimSaveArchive.<init>(ValheimSaveArchive.java:57)
        at net.kakoen.valheim.cli.SaveToolsCLI.readValheimArchive(SaveToolsCLI.java:114)
        at net.kakoen.valheim.cli.SaveToolsCLI.main(SaveToolsCLI.java:52)
```

**Comment by maleneDev** [comment]
Found same issue here https://github.com/Kakoen/valheim-save-tools/issues/79

You've posted in the comments new version which works with new release, however file expired. Can you please post new version once again?
Looking forward to use your tool!

**Comment by Kakoen** [comment]
Closing this, as there is a version available that supports up to world version 34.
