### ISSUE TITLE
Support for world version 34 (Ashlands?)

### ISSUE THREAD

**Issue by b-morgan** [Kakoen/valheim-save-tools#88]
I see a commit for "Experimental support for Save version 32" but I believe Ashlands is now world version 34. Any chance of a release with support for version 34?

C:\Users\Brad\Google Drive\Valheim>java -jar valheim-save-tools-1.1.1.jar Sunlight.db Sunlight.json
INFO Reading from C:\Users\Brad\Google Drive\Valheim\Sunlight.db
WARN WARNING: world version is 34, the maximum tested world version is 29
WARN File not fully read, 46460122 bytes remain
Exception in thread "main" java.lang.IllegalStateException: Failed to read fixed size object at 44, end of object is past end of file
        at net.kakoen.valheim.save.parser.ZPackage.readFixedSizeObject(ZPackage.java:163)
        at net.kakoen.valheim.save.parser.ZPackage.readLengthPrefixedObject(ZPackage.java:190)
        at net.kakoen.valheim.save.archive.save.Zdo.<init>(Zdo.java:79)
        at net.kakoen.valheim.save.archive.ValheimSaveArchive.loadZdos(ValheimSaveArchive.java:101)
        at net.kakoen.valheim.save.archive.ValheimSaveArchive.<init>(ValheimSaveArchive.java:57)
        at net.kakoen.valheim.cli.SaveToolsCLI.readValheimArchive(SaveToolsCLI.java:114)
        at net.kakoen.valheim.cli.SaveToolsCLI.main(SaveToolsCLI.java:52)

**Comment by Gnosh** [comment]
Concur, seeing similar error messages.

**Comment by ijuintekka** [comment]
Compiling the project using the latest commit for version 32 compatibility successfully generates a JSON with no error messages when using version 34 maps. In lieu of a proper update it's at least usable.

**Comment by b-morgan** [comment]
@ijuintekka, I have no idea how to compile the project. Can you attach a .jar file to this issue, please?

**Comment by Kakoen** [comment]
Since @ijuintekka reports it working for them, I've released the version that supports version 32 [here](https://github.com/Kakoen/valheim-save-tools/releases/tag/1.1.2). You can try it with version 34.

When I have more time, I'll look into if there's any changes needed for version 34.

**Comment by b-morgan** [comment]
So far so good. 

Is there any documentation on the .json format?  What I'm looking for is the x,y,z coordinates of all the portals.

**Comment by Kakoen** [comment]
I've released v1.1.3, which should be fully compatible with world version up to 34.
